name: ISP Monitor

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    # Prevent multiple workflows from running simultaneously
    concurrency:
      group: isp-monitor
      cancel-in-progress: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Fetch more history to avoid conflicts
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Run ISP monitor
      run: python scripts/monitor.py
      
    - name: Check for changes and commit
      run: |
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Pull latest changes first to avoid conflicts
        git pull origin main --rebase --autostash
        
        # Add data files
        git add data/
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Commit changes
        git commit -m "Update ISP monitoring data - $(date)"
        
        # Push with retry logic
        for i in {1..3}; do
          if git push origin main; then
            echo "Successfully pushed on attempt $i"
            break
          else
            echo "Push failed on attempt $i, retrying..."
            git pull origin main --rebase --autostash
            sleep 5
          fi
          
          if [ $i -eq 3 ]; then
            echo "Failed to push after 3 attempts"
            exit 1
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
